baseURL = "http://advecti.io"
languageCode = "en-us"
title = "Hi, I'm Hugo running on Kubernetes with multiple replicas!"
theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
