apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: playpen
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 250m
    max:
      memory: 1024Mi
      cpu: 1000m
    min:
      memory: 128Mi
      cpu: 50m
    type: Container